services:
  - type: web
    name: pern-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        value: "https://skillbridge-sand.vercel.app,http://localhost:3000"
    healthCheckPath: /status
    autoDeploy: true
